// Complete Marvel Cinematic Universe (MCU) Roadmap to Avengers: Doomsday (72 Titles)

export const DEFAULT_MARVEL_LIST = [
  // Legacy: WWII & The 1940s
  {
    id: 'mcu-1',
    number: '01',
    type: 'FILM',
    title: 'Captain America: The First Avenger',
    category: 'Legacy: WWII & The 1940s',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: '1 Credit · STOP before credits — the credits scene belongs RIGHT BEFORE The Avengers',
    status: 'unwatched', // 'watched' | 'skipped' | 'unwatched'
  },
  {
    id: 'mcu-2',
    number: '02',
    type: 'SPC',
    title: 'Marvel One-Shot: Agent Carter',
    category: 'Legacy: WWII & The 1940s',
    importance: 'Essential for Doomsday',
    rating: '7.2',
    notes: 'Short film',
    status: 'unwatched',
  },
  {
    id: 'mcu-3',
    number: '03',
    type: 'TV',
    title: 'Agent Carter (Season 1)',
    category: 'Legacy: WWII & The 1940s',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: '8 eps · 1946',
    status: 'unwatched',
  },
  {
    id: 'mcu-4',
    number: '04',
    type: 'TV',
    title: 'Agent Carter (Season 2)',
    category: 'Legacy: WWII & The 1940s',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: '10 eps · 1947 Hollywood',
    status: 'unwatched',
  },

  // Legacy: The Fox X-Men Saga
  {
    id: 'mcu-5',
    number: '05',
    type: 'FILM',
    title: 'X-Men: First Class',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '7.3',
    notes: 'Sets up the origin of Fox X-Men timeline',
    status: 'unwatched',
  },
  {
    id: 'mcu-6',
    number: '06',
    type: 'FILM',
    title: 'X-Men',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '7.0',
    notes: 'Original classic mutants introduction',
    status: 'unwatched',
  },
  {
    id: 'mcu-7',
    number: '07',
    type: 'FILM',
    title: 'X2: X-Men United',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '7.0',
    notes: 'Critical mutant lore and Stryker conflict',
    status: 'unwatched',
  },
  {
    id: 'mcu-8',
    number: '08',
    type: 'FILM',
    title: 'X-Men: The Last Stand',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '6.4',
    notes: 'The Phoenix storyline culmination',
    status: 'unwatched',
  },
  {
    id: 'mcu-9',
    number: '09',
    type: 'FILM',
    title: 'The Wolverine',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '6.4',
    notes: 'Optional — bridges The Last Stand to Days of Future Past',
    status: 'unwatched',
  },
  {
    id: 'mcu-10',
    number: '10',
    type: 'FILM',
    title: 'X-Men: Days of Future Past',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '7.5',
    notes: 'Multiverse time-travel pivotal film',
    status: 'unwatched',
  },
  {
    id: 'mcu-11',
    number: '11',
    type: 'FILM',
    title: 'X-Men: Apocalypse',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '6.5',
    notes: 'Optional — continues the First Class and Days of Future Past timeline',
    status: 'unwatched',
  },
  {
    id: 'mcu-12',
    number: '12',
    type: 'FILM',
    title: 'Dark Phoenix',
    category: 'Legacy: The Fox X-Men Saga',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '6.0',
    notes: 'Optional — the final film of the Fox X-Men saga',
    status: 'unwatched',
  },

  // Legacy: 1990s
  {
    id: 'mcu-13',
    number: '13',
    type: 'FILM',
    title: 'Captain Marvel',
    category: 'Legacy: 1990s',
    importance: 'Essential for Doomsday',
    rating: '6.8',
    notes: '1 Credit · STOP before end-credits — post-credit scene belongs after Infinity War',
    status: 'unwatched',
  },

  // Phase 1 — The Avengers Initiative (2008–2012)
  {
    id: 'mcu-14',
    number: '14',
    type: 'FILM',
    title: 'Iron Man',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '7.7',
    notes: 'Watch all credits · The beginning of the MCU',
    status: 'unwatched',
  },
  {
    id: 'mcu-15',
    number: '15',
    type: 'FILM',
    title: 'The Incredible Hulk',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '6.3',
    notes: 'Watch all credits',
    status: 'unwatched',
  },
  {
    id: 'mcu-16',
    number: '16',
    type: 'FILM',
    title: 'Iron Man 2',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '6.9',
    notes: '1 Credit · STOP before credits — the credits scene belongs RIGHT BEFORE Thor',
    status: 'unwatched',
  },
  {
    id: 'mcu-17',
    number: '17',
    type: 'SPC',
    title: 'Iron Man 2 (Post-Credit Scene)',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: 'Direct bridge to Thor discovery in New Mexico',
    status: 'unwatched',
  },
  {
    id: 'mcu-18',
    number: '18',
    type: 'FILM',
    title: 'Thor',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '6.8',
    notes: '1 Credit · STOP before credits — the credits scene belongs RIGHT BEFORE The Avengers',
    status: 'unwatched',
  },
  {
    id: 'mcu-19',
    number: '19',
    type: 'SPC',
    title: 'Captain America: The First Avenger (Credits)',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: 'Nick Fury approaches Steve in modern day NYC',
    status: 'unwatched',
  },
  {
    id: 'mcu-20',
    number: '20',
    type: 'SPC',
    title: 'Thor (Post-Credit Scene)',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: 'Selvig meets Fury and the Tesseract; Loki reflects',
    status: 'unwatched',
  },
  {
    id: 'mcu-21',
    number: '21',
    type: 'FILM',
    title: 'The Avengers',
    category: 'Phase 1 — The Avengers Initiative',
    importance: 'Essential for Doomsday',
    rating: '8.1',
    notes: 'Watch all credits · Battle of New York',
    status: 'unwatched',
  },

  // Phase 2 — HYDRA & The Infinity Stones (2012–2015)
  {
    id: 'mcu-22',
    number: '22',
    type: 'FILM',
    title: 'Iron Man 3',
    category: 'Phase 2 — HYDRA & The Infinity Stones',
    importance: 'Essential for Doomsday',
    rating: '6.9',
    notes: 'Watch credits · Post-traumatic growth of Tony Stark',
    status: 'unwatched',
  },
  {
    id: 'mcu-23',
    number: '23',
    type: 'FILM',
    title: 'Thor: The Dark World',
    category: 'Phase 2 — HYDRA & The Infinity Stones',
    importance: 'Essential for Doomsday',
    rating: '6.5',
    notes: 'Watch all credits · Reality Stone introduced',
    status: 'unwatched',
  },
  {
    id: 'mcu-24',
    number: '24',
    type: 'FILM',
    title: 'Captain America: The Winter Soldier',
    category: 'Phase 2 — HYDRA & The Infinity Stones',
    importance: 'Essential for Doomsday',
    rating: '7.7',
    notes: 'Watch credits · HYDRA infiltration & Bucky Barnes',
    status: 'unwatched',
  },
  {
    id: 'mcu-25',
    number: '25',
    type: 'FILM',
    title: 'Guardians of the Galaxy',
    category: 'Phase 2 — HYDRA & The Infinity Stones',
    importance: 'Essential for Doomsday',
    rating: '7.9',
    notes: 'Watch both credit scenes · Cosmic MCU & Power Stone',
    status: 'unwatched',
  },
  {
    id: 'mcu-26',
    number: '26',
    type: 'FILM',
    title: 'Guardians of the Galaxy Vol. 2',
    category: 'Phase 2 — HYDRA & The Infinity Stones',
    importance: 'Essential for Doomsday',
    rating: '7.6',
    notes: 'Watch all 5 credits · Celestial ancestry explored',
    status: 'unwatched',
  },

  // Phase 3A — Street Level Heroes (2015–2016)
  {
    id: 'mcu-27',
    number: '27',
    type: 'FILM',
    title: 'Avengers: Age of Ultron',
    category: 'Phase 3A — Street Level Heroes',
    importance: 'Essential for Doomsday',
    rating: '7.3',
    notes: 'Watch mid-credits scene (Thanos decides to do it himself)',
    status: 'unwatched',
  },
  {
    id: 'mcu-28',
    number: '28',
    type: 'FILM',
    title: 'Ant-Man',
    category: 'Phase 3A — Street Level Heroes',
    importance: 'Essential for Doomsday',
    rating: '7.1',
    notes: 'Watch credits · Quantum Realm introduced',
    status: 'unwatched',
  },

  // Phase 3B — Civil War & Fallout (2016–2018)
  {
    id: 'mcu-29',
    number: '29',
    type: 'FILM',
    title: 'Captain America: Civil War',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: 'Watch credits · Avengers fractured',
    status: 'unwatched',
  },
  {
    id: 'mcu-30',
    number: '30',
    type: 'SPC',
    title: 'Team Thor',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Optional for Doomsday',
    rating: '7.2',
    notes: 'Comedic mockumentary — skippable',
    status: 'unwatched',
  },
  {
    id: 'mcu-31',
    number: '31',
    type: 'SPC',
    title: 'Team Thor: Part 2',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Optional for Doomsday',
    rating: '6.9',
    notes: 'Comedic short — skippable',
    status: 'unwatched',
  },
  {
    id: 'mcu-32',
    number: '32',
    type: 'FILM',
    title: 'Black Widow',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '7.2',
    notes: '1 Credit · STOP before end-credits — post-credit belongs right before Hawkeye',
    status: 'unwatched',
  },
  {
    id: 'mcu-33',
    number: '33',
    type: 'TV',
    title: 'Eyes of Wakanda (Season 1)',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '6.2',
    notes: '4 animated eps ~30min · Watch before Black Panther — shows weapon origin',
    status: 'unwatched',
  },
  {
    id: 'mcu-34',
    number: '34',
    type: 'FILM',
    title: 'Black Panther',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '7.4',
    notes: 'Watch credits · Wakanda opens to the world',
    status: 'unwatched',
  },
  {
    id: 'mcu-35',
    number: '35',
    type: 'FILM',
    title: 'Spider-Man: Homecoming',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '7.3',
    notes: 'Watch credits · Peter Parker finds his footing',
    status: 'unwatched',
  },
  {
    id: 'mcu-36',
    number: '36',
    type: 'FILM',
    title: 'Doctor Strange',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    rating: '7.4',
    notes: 'Watch credits · Mystic arts & Time Stone',
    status: 'unwatched',
  },
  {
    id: 'mcu-37',
    number: '37',
    type: 'FILM',
    title: 'Deadpool',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    studio: 'FOX',
    rating: '7.6',
    notes: 'Watch before Deadpool & Wolverine',
    status: 'unwatched',
  },
  {
    id: 'mcu-38',
    number: '38',
    type: 'FILM',
    title: 'Deadpool 2',
    category: 'Phase 3B — Civil War & Fallout',
    importance: 'Essential for Doomsday',
    studio: 'FOX',
    rating: '7.5',
    notes: 'Watch before Deadpool & Wolverine',
    status: 'unwatched',
  },

  // Phase 3C — Ragnarok & The Infinity War (2018)
  {
    id: 'mcu-39',
    number: '39',
    type: 'FILM',
    title: 'Thor: Ragnarok',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Essential for Doomsday',
    rating: '7.6',
    notes: 'Watch credits · Leads straight into Infinity War opening',
    status: 'unwatched',
  },
  {
    id: 'mcu-40',
    number: '40',
    type: 'SPC',
    title: 'Team Darryl',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Optional for Doomsday',
    rating: '6.2',
    notes: 'Comedic short — skippable',
    status: 'unwatched',
  },
  {
    id: 'mcu-41',
    number: '41',
    type: 'FILM',
    title: 'Ant-Man and the Wasp',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Essential for Doomsday',
    rating: '6.9',
    notes: '1 Credit · STOP before credits — the credits scene belongs RIGHT AFTER Infinity War',
    status: 'unwatched',
  },
  {
    id: 'mcu-42',
    number: '42',
    type: 'FILM',
    title: 'Avengers: Infinity War',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Essential for Doomsday',
    rating: '8.2',
    notes: 'Watch main credits · PAUSE before post-credits',
    status: 'unwatched',
  },
  {
    id: 'mcu-43',
    number: '43',
    type: 'SPC',
    title: 'Ant-Man & The Wasp (All Credits)',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: 'Watch NOW immediately after Infinity War — it IS the snap happening in real time',
    status: 'unwatched',
  },
  {
    id: 'mcu-44',
    number: '44',
    type: 'SPC',
    title: 'Captain Marvel (Post-Credits Scene)',
    category: 'Phase 3C — Ragnarok & The Infinity War',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: 'Watch NOW — directly connects to Endgame opening',
    status: 'unwatched',
  },

  // Legacy: Future (2029)
  {
    id: 'mcu-45',
    number: '45',
    type: 'FILM',
    title: 'Logan',
    category: 'Legacy: Future (2029)',
    importance: 'Recommended for Doomsday',
    studio: 'FOX',
    rating: '7.8',
    notes: 'Its ending is the emotional backdrop to Deadpool & Wolverine',
    status: 'unwatched',
  },

  // Phase 4 — The Blip & New Beginnings (2023)
  {
    id: 'mcu-46',
    number: '46',
    type: 'FILM',
    title: 'Avengers: Endgame',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '8.2',
    notes: 'Block out 3 hours · Climax of the Infinity Saga',
    status: 'unwatched',
  },
  {
    id: 'mcu-47',
    number: '47',
    type: 'FILM',
    title: 'Avengers: Endgame Encore',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '8.0',
    notes: '~4 minutes of bridge footage into Doomsday on IMAX/Infinity Vision screens',
    status: 'unwatched',
  },
  {
    id: 'mcu-48',
    number: '48',
    type: 'TV',
    title: 'WandaVision (Season 1)',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '8.2',
    notes: '9 eps · STOP before Ep 9 mid-credit scene',
    status: 'unwatched',
  },
  {
    id: 'mcu-49',
    number: '49',
    type: 'SPC',
    title: 'WandaVision (Ep 9 Mid-Credit Scene)',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '8.0',
    notes: 'Watch NOW immediately after WandaVision Episode 9',
    status: 'unwatched',
  },
  {
    id: 'mcu-50',
    number: '50',
    type: 'TV',
    title: 'The Falcon and the Winter Soldier (Season 1)',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '7.6',
    notes: '6 eps · Legacy of the shield passed to Sam Wilson',
    status: 'unwatched',
  },
  {
    id: 'mcu-51',
    number: '51',
    type: 'TV',
    title: 'Loki (Season 1)',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '8.2',
    notes: '6 eps · Sacred Timeline breaks & Multiverse unleased',
    status: 'unwatched',
  },
  {
    id: 'mcu-52',
    number: '52',
    type: 'TV',
    title: 'What If...? (Season 1)',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Optional for Doomsday',
    rating: '8.0',
    notes: '9 eps · Multiverse animated variants',
    status: 'unwatched',
  },
  {
    id: 'mcu-53',
    number: '53',
    type: 'SPC',
    title: "Peter's To-Do List",
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: 'Watch right before Far From Home',
    status: 'unwatched',
  },
  {
    id: 'mcu-54',
    number: '54',
    type: 'FILM',
    title: 'Spider-Man: Far From Home',
    category: 'Phase 4 — The Blip & New Beginnings',
    importance: 'Essential for Doomsday',
    rating: '7.4',
    notes: 'Watch credits · Peter identity revealed',
    status: 'unwatched',
  },

  // Phase 4 — Multiverse Opens (2024–2025)
  {
    id: 'mcu-55',
    number: '55',
    type: 'SPC',
    title: 'Black Widow (Post-Credit Scene)',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.2',
    notes: 'Watch NOW — directly sets up Hawkeye',
    status: 'unwatched',
  },
  {
    id: 'mcu-56',
    number: '56',
    type: 'TV',
    title: 'Hawkeye (Season 1)',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.8',
    notes: '6 eps · Kate Bishop & Kingpin introduction',
    status: 'unwatched',
  },
  {
    id: 'mcu-57',
    number: '57',
    type: 'FILM',
    title: 'Shang-Chi and the Legend of the Ten Rings',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.5',
    notes: 'Watch credits · Ten Rings cosmic beacon',
    status: 'unwatched',
  },
  {
    id: 'mcu-58',
    number: '58',
    type: 'FILM',
    title: 'Spider-Man: No Way Home',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.9',
    notes: 'Multiverse convergence with Tobey & Andrew',
    status: 'unwatched',
  },
  {
    id: 'mcu-59',
    number: '59',
    type: 'FILM',
    title: 'Doctor Strange: Multiverse of Madness',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.2',
    notes: 'Incursions and Darkhold consequences explored',
    status: 'unwatched',
  },
  {
    id: 'mcu-60',
    number: '60',
    type: 'TV',
    title: 'Ms. Marvel (Season 1)',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Recommended for Doomsday',
    rating: '6.3',
    notes: '6 eps · Quantum bands origin',
    status: 'unwatched',
  },
  {
    id: 'mcu-61',
    number: '61',
    type: 'FILM',
    title: 'Thor: Love and Thunder',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '6.4',
    notes: 'Eternity gate unlocked',
    status: 'unwatched',
  },
  {
    id: 'mcu-62',
    number: '62',
    type: 'FILM',
    title: 'Black Panther: Wakanda Forever',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: 'Namor, Talokan, and Shuri succession',
    status: 'unwatched',
  },
  {
    id: 'mcu-63',
    number: '63',
    type: 'FILM',
    title: 'Ant-Man and the Wasp: Quantumania',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Essential for Doomsday',
    rating: '6.2',
    notes: 'Quantum realm exploration',
    status: 'unwatched',
  },
  {
    id: 'mcu-64',
    number: '64',
    type: 'FILM',
    title: 'The Marvels',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Recommended for Doomsday',
    rating: '5.9',
    notes: 'Incursion tear leads into X-Men dimension',
    status: 'unwatched',
  },
  {
    id: 'mcu-65',
    number: '65',
    type: 'TV',
    title: 'Marvel Zombies',
    category: 'Phase 4 — Multiverse Opens',
    importance: 'Unconfirmed for Doomsday',
    rating: '7.3',
    notes: '4 animated eps',
    status: 'unwatched',
  },

  // Phase 5 — The Multiverse War (2025–2026)
  {
    id: 'mcu-66',
    number: '66',
    type: 'TV',
    title: 'Loki (Season 2)',
    category: 'Phase 5 — The Multiverse War',
    importance: 'Essential for Doomsday',
    rating: '8.2',
    notes: '6 eps · God of Stories holding the multiverse together',
    status: 'unwatched',
  },
  {
    id: 'mcu-67',
    number: '67',
    type: 'FILM',
    title: 'Deadpool & Wolverine',
    category: 'Phase 5 — The Multiverse War',
    importance: 'Essential for Doomsday',
    rating: '7.6',
    notes: 'Watch Logan before this for full impact · Anchor beings and Void',
    status: 'unwatched',
  },
  {
    id: 'mcu-68',
    number: '68',
    type: 'FILM',
    title: 'Captain America: Brave New World',
    category: 'Phase 5 — The Multiverse War',
    importance: 'Essential for Doomsday',
    rating: '6.0',
    notes: 'Red Hulk & global political conflicts',
    status: 'unwatched',
  },
  {
    id: 'mcu-69',
    number: '69',
    type: 'FILM',
    title: 'Thunderbolts*',
    category: 'Phase 5 — The Multiverse War',
    importance: 'Essential for Doomsday',
    rating: '7.3',
    notes: 'Sentry & anti-hero squad assembled',
    status: 'unwatched',
  },

  // Phase 6 — Doomsday (2026)
  {
    id: 'mcu-70',
    number: '70',
    type: 'FILM',
    title: 'Spider-Man: Brand New Day',
    category: 'Phase 6 — Doomsday',
    importance: 'Recommended for Doomsday',
    rating: '8.0',
    notes: 'Street level Spidey reset',
    status: 'unwatched',
  },
  {
    id: 'mcu-71',
    number: '71',
    type: 'FILM',
    title: 'The Fantastic Four: First Steps',
    category: 'Phase 6 — Doomsday',
    importance: 'Essential for Doomsday',
    rating: '7.0',
    notes: '1960s retro-future universe introduction to Doom & Galactus',
    status: 'unwatched',
  },
  {
    id: 'mcu-72',
    number: '72',
    type: 'FILM',
    title: 'AVENGERS: DOOMSDAY',
    category: 'Phase 6 — Doomsday',
    importance: 'Essential for Doomsday',
    rating: '9.0',
    notes: '🔥 The Ultimate Culmination · Robert Downey Jr. as Doctor Doom',
    status: 'unwatched',
  },
];

export const DEFAULT_CUSTOM_LISTS = [
  {
    id: 'list-mcu-doomsday',
    title: 'Marvel: Road to Avengers Doomsday',
    description: 'Complete 72-title chronological MCU watch guide',
    icon: 'Clapperboard',
    color: '#ef4444',
    items: DEFAULT_MARVEL_LIST,
  }
];
