/**
 * 20 OIL-FREE SOUPS FOR WEIGHT MANAGEMENT
 * Tamil Nadu Local-Market Ingredients • Measured Portions • Calorie-Tracker Friendly
 *
 * Designed for night diet / dinner routines to create sustainable calorie deficits.
 * Zero oil, ghee, or butter. Uses water, pepper, cumin, turmeric, chilli, coriander,
 * curry leaves, ginger, garlic, lemon, and measured salt.
 */

import { syncToCloud } from './firebase';

export const NIGHT_DIET_SOUPS = [
  {
    id: 'soup-1',
    name: 'Mixed Vegetable & Moong Soup',
    tamilName: 'பச்சை பயிறு காய்கறி சூப்',
    emoji: '🍲',
    category: 'Vegetarian',
    categoryTag: 'Lentils & Dal',
    calories: 155,
    protein: 9.0,
    carbs: 27,
    fibre: 6,
    fats: 0.5,
    servingSize: '1 large bowl (~400–450 ml)',
    servingGrams: 420,
    waterMl: 400,
    description: 'Hearty high-fibre dinner soup packed with yellow moong dal and freshly diced local market vegetables.',
    ingredients: [
      { item: 'Moong dal (dry)', amount: '25 g' },
      { item: 'Tomato', amount: '75 g' },
      { item: 'Carrot', amount: '50 g' },
      { item: 'French Beans', amount: '50 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
      { item: 'Ginger', amount: '5 g' },
    ],
    method: 'Pressure-cook moong dal with 400 ml water. Add finely chopped vegetables, grated ginger and crushed garlic; simmer 8–10 minutes. Lightly mash the dal and vegetables with a ladle. Add pepper, cumin powder, and salt.',
    seasoning: 'Crushed black pepper + roasted cumin powder + turmeric + fresh coriander leaves + curry leaves + small pinch of salt. Squeeze half a lemon after turning off heat.',
    tags: ['Vegetarian', 'High Fibre', 'Dal Based', 'High Satiety'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Sunday',
  },
  {
    id: 'soup-2',
    name: 'Tomato–Carrot Pepper Soup',
    tamilName: 'தக்காளி கேரட் மிளகு சூப்',
    emoji: '🍅',
    category: 'Vegetarian',
    categoryTag: 'Ultra Light',
    calories: 95,
    protein: 2.5,
    carbs: 19,
    fibre: 5,
    fats: 0.2,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 450,
    waterMl: 450,
    description: 'Under 100 kcal light night soup rich in lycopene and beta-carotene with a zesty black pepper kick.',
    ingredients: [
      { item: 'Ripe Country Tomato', amount: '200 g' },
      { item: 'Carrot', amount: '80 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Roughly chop tomatoes, carrot, onion, and garlic. Boil in 450 ml water until thoroughly soft. Blend using an immersion hand blender until smooth and velvety. Return to pan, season with freshly crushed pepper, cumin, and salt; simmer 2 minutes.',
    seasoning: 'Coarsely ground black pepper + cumin powder + turmeric + fresh coriander garnish + minimal salt. Optional splash of lemon.',
    tags: ['Under 100 kcal', 'Ultra Light', 'Vitamin A & C', 'Fast Digesting'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Wednesday',
  },
  {
    id: 'soup-3',
    name: 'Keerai (Greens) & Moong Soup',
    tamilName: 'கீரை பாசிப்பருப்பு சூப் (அரைக்கீரை / பாலக்)',
    emoji: '🥬',
    category: 'Vegetarian',
    categoryTag: 'Greens & Keerai',
    calories: 125,
    protein: 8.5,
    carbs: 20,
    fibre: 5,
    fats: 0.5,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 410,
    waterMl: 400,
    description: 'Iron-packed local greens (spinach, arai keerai, or siru keerai) simmered with light yellow moong dal.',
    ingredients: [
      { item: 'Spinach / Arai Keerai (cleaned)', amount: '120 g' },
      { item: 'Moong dal (dry)', amount: '25 g' },
      { item: 'Tomato', amount: '75 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Cook moong dal with water until tender and soft. Add washed chopped keerai, tomato, onion, and crushed garlic; simmer 6–8 minutes. Blend partially or fully with a whisk/blender for desired texture. Season with pepper, cumin, and salt.',
    seasoning: 'Roasted cumin + black pepper + turmeric + curry leaves + rock salt. Lemon juice at the end prevents iron loss.',
    tags: ['Greens / Keerai', 'High Iron', 'High Protein', 'Blood Purifier'],
    isHighProtein: true,
    isLowCalorie: true,
    dayOfWeek: 'Tuesday',
  },
  {
    id: 'soup-4',
    name: 'Murungai Keerai Lentil Soup',
    tamilName: 'முருங்கைக்கீரை பருப்பு சூப்',
    emoji: '🌿',
    category: 'Vegetarian',
    categoryTag: 'Greens & Keerai',
    calories: 140,
    protein: 9.0,
    carbs: 22,
    fibre: 5,
    fats: 0.5,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 420,
    waterMl: 400,
    description: 'Tamil Nadu superfood drumstick leaves with masoor dal. Exceptional source of plant protein, calcium, and iron.',
    ingredients: [
      { item: 'Fresh Drumstick Leaves (Murungai)', amount: '80 g' },
      { item: 'Masoor dal (dry)', amount: '25 g' },
      { item: 'Tomato', amount: '80 g' },
      { item: 'Onion', amount: '25 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Cook red masoor dal in water until soft. Add washed murungai leaves, chopped tomato, onion, and crushed garlic; simmer 8 minutes until leaves are tender. Mash lightly with mathu or blend lightly. Season with crushed pepper and roasted cumin.',
    seasoning: 'Black pepper + cumin + turmeric + curry leaves + light salt. Fresh lemon juice added before serving.',
    tags: ['Greens / Keerai', 'Tamil Superfood', 'Calcium & Iron Rich', 'High Protein'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Friday',
  },
  {
    id: 'soup-5',
    name: 'Chow Chow Moong Soup',
    tamilName: 'சௌ சௌ பாசிப்பருப்பு சூப்',
    emoji: '🥣',
    category: 'Vegetarian',
    categoryTag: 'Hydrating Vegetables',
    calories: 135,
    protein: 8.0,
    carbs: 24,
    fibre: 4,
    fats: 0.4,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 430,
    waterMl: 400,
    description: 'High-water-content local chow chow (chayote) with moong dal for gentle nighttime digestion and satiety.',
    ingredients: [
      { item: 'Chow Chow (peeled, diced)', amount: '180 g' },
      { item: 'Moong dal (dry)', amount: '25 g' },
      { item: 'Tomato', amount: '60 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Fresh Ginger', amount: '5 g' },
    ],
    method: 'Cook moong dal separately. In a pot, add diced chow chow, tomato, onion, and ginger with 400 ml water; simmer until tender. Combine cooked dal, mash lightly with a ladle for rustic body. Season with pepper, cumin, and salt.',
    seasoning: 'Cumin powder + crushed black pepper + turmeric + coriander leaves + salt.',
    tags: ['Hydrating', 'Tamil Nadu Local', 'Gentle on Gut', 'Low Calorie'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Thursday',
  },
  {
    id: 'soup-6',
    name: 'Bottle Gourd (Sorakkai) Dal Soup',
    tamilName: 'சுரைக்காய் துவரம்பருப்பு சூப்',
    emoji: '🥒',
    category: 'Vegetarian',
    categoryTag: 'Hydrating Vegetables',
    calories: 150,
    protein: 8.0,
    carbs: 25,
    fibre: 5,
    fats: 0.5,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 460,
    waterMl: 400,
    description: 'Traditional cooling sorakkai and protein-rich toor dal. Keeps body light and eliminates water retention.',
    ingredients: [
      { item: 'Bottle Gourd / Sorakkai (diced)', amount: '200 g' },
      { item: 'Toor dal (dry)', amount: '25 g' },
      { item: 'Tomato', amount: '60 g' },
      { item: 'Garlic', amount: '5 g' },
      { item: 'Cumin seeds', amount: '1 g' },
    ],
    method: 'Pressure-cook toor dal and bottle gourd pieces together with tomato, garlic, and 400 ml water for 3 whistles. Mash well with a wooden masher. Add cumin, pepper, turmeric, and salt; boil 2–3 minutes.',
    seasoning: 'Crushed cumin seeds + black pepper + turmeric + fresh curry leaves + small amount of salt.',
    tags: ['Cooling', 'Water Dense', 'Anti-Bloat', 'Digestive Health'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Saturday',
  },
  {
    id: 'soup-7',
    name: 'Pumpkin Moong Soup',
    tamilName: 'மஞ்சள் பூசணி பாசிப்பருப்பு சூப்',
    emoji: '🎃',
    category: 'Vegetarian',
    categoryTag: 'Lentils & Dal',
    calories: 135,
    protein: 7.0,
    carbs: 25,
    fibre: 4,
    fats: 0.4,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 450,
    waterMl: 450,
    description: 'Naturally sweet and creamy yellow pumpkin (parangikai) blended with moong dal—zero cream or butter needed.',
    ingredients: [
      { item: 'Yellow Pumpkin / Parangikai', amount: '220 g' },
      { item: 'Moong dal (dry)', amount: '20 g' },
      { item: 'Tomato', amount: '50 g' },
      { item: 'Ginger', amount: '5 g' },
    ],
    method: 'Cook diced pumpkin and moong dal with 450 ml water until completely soft. Puree using a blender until silky smooth. Return to pot, add ginger, freshly cracked pepper, cumin, and salt; simmer briefly for 2 minutes.',
    seasoning: 'Coarse pepper + roasted jeera + ginger juice + coriander garnish.',
    tags: ['Creamy Without Cream', 'Beta-Carotene', 'Eye Health', 'Comfort Food'],
    isHighProtein: false,
    isLowCalorie: false,
    dayOfWeek: 'Monday',
  },
  {
    id: 'soup-8',
    name: 'Cauliflower Pepper Soup',
    tamilName: 'காலிஃபிளவர் மிளகு சூப்',
    emoji: '🥦',
    category: 'Vegetarian',
    categoryTag: 'Low Carb Comfort',
    calories: 125,
    protein: 7.0,
    carbs: 18,
    fibre: 5,
    fats: 1.5,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 410,
    waterMl: 250,
    description: 'Thick, creamy texture achieved by blending tender cauliflower florets with toned milk and fiery South Indian black pepper.',
    ingredients: [
      { item: 'Cauliflower florets', amount: '220 g' },
      { item: 'Onion', amount: '40 g' },
      { item: 'Tomato', amount: '60 g' },
      { item: 'Garlic', amount: '5 g' },
      { item: 'Toned Milk (cow milk)', amount: '50 g' },
    ],
    method: 'Steam or boil cauliflower florets with onion, tomato, and garlic until tender. Blend into a rich puree. Return to pot, add 50g toned milk and 100 ml water; simmer gently on low flame. Season with generous black pepper and salt.',
    seasoning: 'Fresh black pepper + garlic aroma + pinch of salt + coriander.',
    tags: ['Low Carb', 'Creamy Comfort', 'Keto Friendly', 'Cruciferous Power'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Thursday',
  },
  {
    id: 'soup-9',
    name: 'Cabbage–Peas Soup',
    tamilName: 'முட்டைக்கோஸ் பச்சை பட்டாணி சூப்',
    emoji: '🥗',
    category: 'Vegetarian',
    categoryTag: 'High Fibre Crunch',
    calories: 145,
    protein: 7.0,
    carbs: 26,
    fibre: 6,
    fats: 0.4,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 460,
    waterMl: 450,
    description: 'Shredded local cabbage and sweet green peas offering exceptional gut-healthy prebiotic fibre and fullness.',
    ingredients: [
      { item: 'Cabbage (shredded)', amount: '150 g' },
      { item: 'Fresh Green Peas', amount: '60 g' },
      { item: 'Tomato', amount: '70 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Boil shredded cabbage, green peas, tomato, onion, and garlic with 450 ml water until tender. Blend half of the soup for body while leaving the rest chunky for pleasant mouthfeel. Season with pepper, cumin, and salt; simmer 2 minutes.',
    seasoning: 'Crushed black pepper + cumin powder + turmeric + fresh coriander.',
    tags: ['High Fibre', 'Prebiotic', 'Gut Friendly', 'Chunky Texture'],
    isHighProtein: false,
    isLowCalorie: false,
    dayOfWeek: 'Saturday',
  },
  {
    id: 'soup-10',
    name: 'Vegetable–Horse Gram Soup',
    tamilName: 'கொள்ளு காய்கறி சூப்',
    emoji: '🌾',
    category: 'Vegetarian',
    categoryTag: 'Traditional Kollu',
    calories: 175,
    protein: 10.0,
    carbs: 30,
    fibre: 6,
    fats: 0.8,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 450,
    waterMl: 400,
    description: 'Renowned Tamil Nadu fat-loss legume (Kollu) simmered with mixed vegetables. Strong thermogenic satiety.',
    ingredients: [
      { item: 'Kollu / Horse Gram (boiled)', amount: '70 g' },
      { item: 'Carrot', amount: '60 g' },
      { item: 'Tomato', amount: '80 g' },
      { item: 'Cabbage', amount: '60 g' },
      { item: 'Onion', amount: '25 g' },
    ],
    method: 'Use pre-soaked, well-cooked horse gram. In a pot, combine cooked kollu with diced vegetables and 400 ml water; simmer 10 minutes. Blend 1/4th of the soup to give a hearty rustic broth. Add pepper, cumin, and salt.',
    seasoning: 'Dry-roasted cumin + pepper + turmeric + curry leaves + lemon juice.',
    tags: ['Traditional Kollu', 'High Protein', 'Thermogenic', 'High Satiety'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Monday',
  },
  {
    id: 'soup-11',
    name: 'Kollu Rasam-Style Soup',
    tamilName: 'கொள்ளு ரசம் சூப் (பாரம்பரிய முறை)',
    emoji: '🍵',
    category: 'Vegetarian',
    categoryTag: 'Traditional Kollu',
    calories: 125,
    protein: 7.0,
    carbs: 21,
    fibre: 5,
    fats: 0.5,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 450,
    waterMl: 350,
    description: 'Thin, aromatic Tamil-style rasam soup with horse gram stock, garlic, and fresh cumin-pepper podi.',
    ingredients: [
      { item: 'Kollu / Horse Gram (boiled)', amount: '60 g' },
      { item: 'Tomato (mashed)', amount: '150 g' },
      { item: 'Garlic cloves (crushed)', amount: '5 g' },
      { item: 'Whole Cumin', amount: '1 g' },
      { item: 'Black Pepper', amount: '1 g' },
    ],
    method: 'Blend cooked kollu with tomato and 350 ml water. In a pot, boil the mixture with crushed garlic, freshly pounded cumin, black pepper, and salt for 5–7 minutes until aromatic. Keep it delightfully thin, spicy, and soupy.',
    seasoning: 'Pounded jeera + milagu + curry leaves + coriander + hing pinch + lemon juice.',
    tags: ['Rasam Style', 'Traditional TN', 'Thermogenic', 'Cold & Cough Relief'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Friday',
  },
  {
    id: 'soup-12',
    name: 'Mushroom Pepper Soup',
    tamilName: 'காளான் மிளகு சூப்',
    emoji: '🍄',
    category: 'Vegetarian',
    categoryTag: 'Umami Rich',
    calories: 120,
    protein: 8.0,
    carbs: 15,
    fibre: 5,
    fats: 1.5,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 400,
    waterMl: 350,
    description: 'Savory button/oyster mushrooms simmered in aromatic garlic-pepper broth with a touch of toned milk.',
    ingredients: [
      { item: 'Button / Oyster Mushrooms', amount: '180 g' },
      { item: 'Onion', amount: '40 g' },
      { item: 'Tomato', amount: '50 g' },
      { item: 'Garlic', amount: '5 g' },
      { item: 'Toned Milk', amount: '50 g' },
    ],
    method: 'Slice mushrooms. Boil mushrooms, onion, tomato, and garlic with 350 ml water for 6 minutes. Blend roughly one-third of the soup for texture, return to pot. Add toned milk, freshly ground black pepper, and salt; simmer 2 minutes.',
    seasoning: 'Fresh crushed black pepper + garlic aroma + coriander + salt.',
    tags: ['Umami Rich', 'Low Calorie', 'High Protein', 'Immune Boosting'],
    isHighProtein: true,
    isLowCalorie: true,
    dayOfWeek: 'Saturday',
  },
  {
    id: 'soup-13',
    name: 'Chicken–Vegetable Clear Soup',
    tamilName: 'கோழி காய்கறி கிளியர் சூப்',
    emoji: '🍗',
    category: 'Non-Vegetarian',
    categoryTag: 'Lean Protein Powerhouse',
    calories: 190,
    protein: 29.0,
    carbs: 12,
    fibre: 4,
    fats: 2.0,
    servingSize: '1 large bowl (~500 ml)',
    servingGrams: 510,
    waterMl: 500,
    description: 'Ultimate 29g lean protein dinner soup using shredded skinless chicken breast and crunchy farm vegetables. Zero oil or commercial stock cubes.',
    ingredients: [
      { item: 'Chicken Breast (skinless, raw)', amount: '100 g' },
      { item: 'Carrot', amount: '50 g' },
      { item: 'French Beans', amount: '50 g' },
      { item: 'Cabbage', amount: '50 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Boil chicken breast in 500 ml water with crushed garlic and sliced onion for 12–15 minutes until fully cooked. Remove chicken, shred finely with two forks, and return to broth. Add chopped vegetables and simmer 7–8 minutes until tender-crisp. Season with pepper and salt.',
    seasoning: 'Coarse black pepper + ginger juliennes + coriander leaves + lemon wedge squeeze.',
    tags: ['Non-Veg', '29g Protein', 'Muscle Recovery', 'Maximum Satiety'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Monday',
  },
  {
    id: 'soup-14',
    name: 'Egg Drop Vegetable Soup',
    tamilName: 'முட்டை காய்கறி சூப்',
    emoji: '🍳',
    category: 'Eggetarian',
    categoryTag: 'Quick Comfort',
    calories: 140,
    protein: 9.0,
    carbs: 17,
    fibre: 5,
    fats: 4.5,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 460,
    waterMl: 450,
    description: 'Silky ribbons of whole farm egg drizzled into a boiling peppered vegetable broth. Ready in 10 minutes.',
    ingredients: [
      { item: 'Whole Farm Egg (beaten)', amount: '1 egg (~50 g)' },
      { item: 'Cabbage (fine shredded)', amount: '80 g' },
      { item: 'Carrot (julienned)', amount: '50 g' },
      { item: 'French Beans', amount: '50 g' },
      { item: 'Tomato', amount: '60 g' },
      { item: 'Onion', amount: '25 g' },
    ],
    method: 'Boil chopped vegetables in 450 ml water with salt and turmeric until tender. Beat 1 egg thoroughly in a bowl. While stirring the simmering soup continuously in a circular motion, slowly drizzle the beaten egg in a thin stream to form delicate egg ribbons. Cook 1–2 minutes; season with pepper.',
    seasoning: 'Black pepper + pinch of cumin + coriander leaves + salt.',
    tags: ['Eggetarian', 'Quick 10 Min', 'Silky Ribbons', 'Good Fats'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Wednesday',
  },
  {
    id: 'soup-15',
    name: 'Fish & Vegetable Soup',
    tamilName: 'மீன் காய்கறி சூப்',
    emoji: '🐟',
    category: 'Non-Vegetarian',
    categoryTag: 'Lean Protein & Omega-3',
    calories: 175,
    protein: 24.0,
    carbs: 13,
    fibre: 5,
    fats: 2.0,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 470,
    waterMl: 450,
    description: 'Light, delicate lean fish fillets cooked with tomato and garlic. Rich in 24g protein and brain-boosting omega-3.',
    ingredients: [
      { item: 'Lean White Fish / Vanjaram (cleaned)', amount: '100 g' },
      { item: 'Tomato', amount: '80 g' },
      { item: 'Carrot', amount: '50 g' },
      { item: 'French Beans', amount: '50 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Simmer cleaned fish fillets in 450 ml water with sliced onion, crushed garlic, and chopped tomato for 6–8 minutes. Add diced vegetables and simmer until vegetables are tender and fish flakes easily. Remove any bones if necessary. Season with pepper, turmeric, and sea salt.',
    seasoning: 'Fresh black pepper + turmeric + curry leaves + squeeze of lemon juice.',
    tags: ['Non-Veg', '24g Protein', 'Omega-3', 'Metabolism Boost'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Thursday',
  },
  {
    id: 'soup-16',
    name: 'Green Peas & Mint Soup',
    tamilName: 'பட்டாணி புதினா சூப்',
    emoji: '🌱',
    category: 'Vegetarian',
    categoryTag: 'Aromatic & Fresh',
    calories: 145,
    protein: 8.0,
    carbs: 25,
    fibre: 6,
    fats: 0.5,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 410,
    waterMl: 400,
    description: 'Vibrant green peas pureed with fresh pudina (mint) leaves for a cooling, refreshing digestive dinner.',
    ingredients: [
      { item: 'Green Peas (fresh/frozen)', amount: '120 g' },
      { item: 'Fresh Mint Leaves (Pudina)', amount: '10 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Tomato', amount: '50 g' },
      { item: 'Garlic', amount: '5 g' },
    ],
    method: 'Boil green peas, onion, tomato, and garlic with 400 ml water until peas are soft and tender. Add fresh mint leaves right at the end to keep their vibrant green color and aroma. Blend until velvety smooth. Simmer 2 minutes with pepper, roasted cumin, and salt.',
    seasoning: 'Roasted cumin + black pepper + fresh mint aroma + lemon juice.',
    tags: ['Aromatic & Fresh', 'Digestion Friendly', 'High Fibre', 'Vibrant Green'],
    isHighProtein: true,
    isLowCalorie: false,
    dayOfWeek: 'Tuesday',
  },
  {
    id: 'soup-17',
    name: 'Beetroot–Carrot Soup',
    tamilName: 'பீட்ரூட் கேரட் சூப்',
    emoji: '🫐',
    category: 'Vegetarian',
    categoryTag: 'Detox & Stamina',
    calories: 115,
    protein: 3.0,
    carbs: 25,
    fibre: 5,
    fats: 0.3,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 460,
    waterMl: 450,
    description: 'Vibrant ruby soup loaded with natural dietary nitrates for blood circulation, cellular stamina, and skin radiance.',
    ingredients: [
      { item: 'Beetroot (peeled, chopped)', amount: '100 g' },
      { item: 'Carrot (chopped)', amount: '100 g' },
      { item: 'Tomato', amount: '70 g' },
      { item: 'Onion', amount: '25 g' },
      { item: 'Ginger', amount: '5 g' },
    ],
    method: 'Boil beetroot, carrot, tomato, onion, and fresh ginger in 450 ml water until thoroughly soft. Puree using an immersion blender until velvety smooth. Return to pot, add pepper, cumin, and salt. Avoid adding any sugar—the root vegetables provide natural gentle sweetness.',
    seasoning: 'Crushed black pepper + cumin powder + ginger heat + splash of lemon.',
    tags: ['Detox & Stamina', 'Blood Flow Nitrates', 'Skin Glow', 'Low Calorie'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Wednesday',
  },
  {
    id: 'soup-18',
    name: 'Radish–Tomato Soup',
    tamilName: 'முள்ளங்கி தக்காளி சூப்',
    emoji: '🥣',
    category: 'Vegetarian',
    categoryTag: 'Diuretic & Cleansing',
    calories: 115,
    protein: 6.0,
    carbs: 20,
    fibre: 4,
    fats: 0.4,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 410,
    waterMl: 400,
    description: 'Country white radish (mullangi) simmered with moong dal and tomato. Excellent natural diuretic to flush water retention.',
    ingredients: [
      { item: 'Radish / Mullangi (sliced)', amount: '180 g' },
      { item: 'Tomato', amount: '100 g' },
      { item: 'Onion', amount: '30 g' },
      { item: 'Garlic', amount: '5 g' },
      { item: 'Moong dal (dry)', amount: '15 g' },
    ],
    method: 'Cook moong dal in water until soft. Add sliced radish, tomato, onion, and garlic; simmer 10 minutes until radish turns completely translucent and mellow. Blend partially to retain rustic texture. Season with black pepper, cumin, and salt.',
    seasoning: 'Black pepper + cumin + turmeric + curry leaves + lemon juice.',
    tags: ['Diuretic', 'Water Retention Flush', 'Low Calorie', 'Mellow Flavour'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Sunday',
  },
  {
    id: 'soup-19',
    name: 'Ridge Gourd (Peerkangai) Soup',
    tamilName: 'பீர்க்கங்காய் பாசிப்பருப்பு சூப்',
    emoji: '🥒',
    category: 'Vegetarian',
    categoryTag: 'Cooling & Gentle',
    calories: 120,
    protein: 7.0,
    carbs: 21,
    fibre: 4,
    fats: 0.4,
    servingSize: '1 large bowl (~400 ml)',
    servingGrams: 420,
    waterMl: 380,
    description: 'High-cellulose, water-dense peerkangai simmered with light dal and ginger for effortless nighttime digestion.',
    ingredients: [
      { item: 'Ridge Gourd / Peerkangai (peeled, chopped)', amount: '220 g' },
      { item: 'Moong dal (dry)', amount: '20 g' },
      { item: 'Tomato', amount: '60 g' },
      { item: 'Onion', amount: '25 g' },
      { item: 'Ginger', amount: '5 g' },
    ],
    method: 'Cook moong dal in water. Add peeled and chopped ridge gourd, tomato, onion, and ginger with 350–400 ml water. Simmer until ridge gourd turns tender and soft. Blend lightly with a mathu or pulse twice. Season with pepper, cumin, and salt.',
    seasoning: 'Crushed black pepper + cumin powder + curry leaves + coriander.',
    tags: ['Cooling & Gentle', 'High Water Content', 'Low Calorie', 'Alkalizing'],
    isHighProtein: false,
    isLowCalorie: true,
    dayOfWeek: 'Tuesday',
  },
  {
    id: 'soup-20',
    name: 'Mixed Millet Vegetable Soup',
    tamilName: 'திணை சிறுதானிய காய்கறி சூப்',
    emoji: '🌾',
    category: 'Vegetarian',
    categoryTag: 'Ancient Millets',
    calories: 175,
    protein: 7.0,
    carbs: 31,
    fibre: 5,
    fats: 0.8,
    servingSize: '1 large bowl (~450 ml)',
    servingGrams: 460,
    waterMl: 400,
    description: 'Ancient foxtail millet (thinai) combined with crunchy garden vegetables and moong dal for slow-burning complex carbs.',
    ingredients: [
      { item: 'Cooked Foxtail Millet (Thinai)', amount: '60 g' },
      { item: 'Carrot', amount: '50 g' },
      { item: 'French Beans', amount: '50 g' },
      { item: 'Cabbage', amount: '60 g' },
      { item: 'Tomato', amount: '70 g' },
      { item: 'Moong dal (dry)', amount: '15 g' },
    ],
    method: 'Cook moong dal. Add chopped vegetables and 400 ml water; simmer 8–10 minutes. Add cooked foxtail millet, pepper, cumin, and salt. Simmer 2 minutes. Do not over-thicken so it remains an easy, comforting soup.',
    seasoning: 'Roasted cumin + black pepper + turmeric + curry leaves + coriander.',
    tags: ['Ancient Millets', 'Complex Carbs', 'Diabetic Friendly', 'High Fibre'],
    isHighProtein: false,
    isLowCalorie: false,
    dayOfWeek: 'Friday',
  },
];

/**
 * Weekly rotation recommendation
 */
export const WEEKLY_SOUP_ROTATION = [
  { day: 'Monday', soupId: 'soup-13', name: 'Chicken–Vegetable Clear Soup', vegAltId: 'soup-10', vegAltName: 'Vegetable–Horse Gram Soup', focus: 'High Protein / Lean Kickoff' },
  { day: 'Tuesday', soupId: 'soup-3', name: 'Keerai (Greens) & Moong Soup', vegAltId: 'soup-19', vegAltName: 'Ridge Gourd Moong Soup', focus: 'Iron, Greens & Alkalizing' },
  { day: 'Wednesday', soupId: 'soup-2', name: 'Tomato–Carrot Pepper Soup', vegAltId: 'soup-14', vegAltName: 'Egg Drop Vegetable Soup', focus: 'Under 100 kcal / Lycopene' },
  { day: 'Thursday', soupId: 'soup-15', name: 'Fish & Vegetable Soup', vegAltId: 'soup-5', vegAltName: 'Chow Chow Moong Soup', focus: 'Omega-3 & Gentle Hydration' },
  { day: 'Friday', soupId: 'soup-11', name: 'Kollu Rasam-Style Soup', vegAltId: 'soup-4', vegAltName: 'Murungai Keerai Lentil Soup', focus: 'Traditional Thermogenic Kollu' },
  { day: 'Saturday', soupId: 'soup-12', name: 'Mushroom Pepper Soup', vegAltId: 'soup-9', vegAltName: 'Cabbage–Peas Soup', focus: 'Umami Rich & Prebiotic Fibre' },
  { day: 'Sunday', soupId: 'soup-1', name: 'Mixed Vegetable & Moong Soup', vegAltId: 'soup-18', vegAltName: 'Radish–Tomato Soup', focus: 'High-Fibre Weekend Reset' },
];

/**
 * Practical weight management tips from nutrition protocol
 */
export const SOUP_WEIGHT_LOSS_TIPS = [
  {
    title: 'Meal Component, Not Extra Food',
    desc: 'Use soup as the core dinner dish rather than having it before a full, heavy meal. A 150 kcal soup is a powerful weight-management tool when replacing heavy dinner carbs.',
    icon: 'Moon',
  },
  {
    title: 'Zero Added Oil, Ghee or Butter',
    desc: 'Prepared without frying or tadka in oil. Uses water-boiling, garlic, ginger, pepper, cumin, turmeric, and lemon for maximum aroma without hidden 100+ liquid fat calories.',
    icon: 'ShieldCheck',
  },
  {
    title: 'High Protein For Overnight Satiety',
    desc: 'Choose protein-dense soups (Chicken Clear 29g, Fish 24g, Horse Gram 10g, Murungai 9g, Moong 9g) to prevent midnight snack cravings and preserve lean muscle mass.',
    icon: 'Flame',
  },
  {
    title: 'Moderate Sodium to Avoid Bloat',
    desc: 'Keep salt measured and modest. Generous black pepper, cumin, and lemon provide robust flavour without causing next-morning water retention.',
    icon: 'Droplets',
  },
];

/**
 * Helper to get today's recommended soup
 */
export const getTodaySoupRotation = (date = new Date()) => {
  const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const dayName = typeof date === 'string' 
    ? dayNames[new Date(date).getDay()] 
    : dayNames[date.getDay()];
  
  const rotation = WEEKLY_SOUP_ROTATION.find(r => r.day === dayName) || WEEKLY_SOUP_ROTATION[0];
  const primarySoup = NIGHT_DIET_SOUPS.find(s => s.id === rotation.soupId);
  const vegAltSoup = NIGHT_DIET_SOUPS.find(s => s.id === rotation.vegAltId);

  return {
    dayName,
    rotation,
    primarySoup,
    vegAltSoup,
  };
};

/**
 * Helper to log soup to user's daily meals in localStorage
 */
export const logSoupToDailyMeals = (soup, mealType = 'dinner', dateStr = new Date().toISOString().split('T')[0], userId = 'default_user') => {
  try {
    const key = `life_tracker_meals_${userId}_${dateStr}`;
    const raw = localStorage.getItem(key);
    const existing = raw ? JSON.parse(raw) : [];

    const newEntry = {
      id: `soup-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
      mealType,
      name: soup.name,
      icon: soup.emoji || '🍲',
      servingGrams: soup.servingGrams || 400,
      servingLabel: soup.servingSize || '1 bowl (~350–500ml)',
      calories: Math.round(soup.calories),
      protein: soup.protein,
      carbs: soup.carbs,
      fats: soup.fats || 0.5,
      fibre: soup.fibre,
      multiplier: 1,
      isNightDietSoup: true,
      timestamp: Date.now(),
    };

    const updated = [...existing, newEntry];
    localStorage.setItem(key, JSON.stringify(updated));

    // Real-time Cloud Sync: Push logged meal directly to user's Firebase Firestore document
    try {
      syncToCloud(userId, {
        [`dailyMeals_${dateStr}`]: updated,
        lastMealLoggedAt: new Date().toISOString()
      });
    } catch (cloudErr) {
      console.warn('Firebase cloud meal sync skipped (offline mode):', cloudErr);
    }

    return { success: true, entry: newEntry, count: updated.length };
  } catch (e) {
    console.error('Failed to log soup meal:', e);
    return { success: false, error: e };
  }
};
