// Career Roadmap Data (Sep 1 to Dec 31, 2026) matching your exact 16-week Excel curriculum

export const DEFAULT_ROADMAP = [
  {
    id: 'sep-w1',
    period: 'Sep W1',
    month: 'September',
    dateRange: 'Sep 1 - Sep 7',
    dsa: 'Big-O, arrays, two pointers',
    fullstack: 'React fundamentals, components, JSX',
    mobile: 'RN setup, environment (CLI / Expo), core components',
    project: 'Refactor one existing UI into clean modular components',
    career: 'Git/GitHub portfolio setup, profile audit',
    status: 'In Progress',
    completedTasks: ['dsa'],
    isLightWeek: false,
    notes: 'Focus on core array algorithms and clean Git commit history.',
  },
  {
    id: 'sep-w2',
    period: 'Sep W2',
    month: 'September',
    dateRange: 'Sep 8 - Sep 14',
    dsa: 'Hash maps, frequency counters, sliding window',
    fullstack: 'Hooks, forms, state management (Context/Zustand)',
    mobile: 'Flexbox, styling, responsive mobile layouts',
    project: 'Build a small interactive component dashboard',
    career: 'Explain React lifecycle & state management in mock',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'sep-w3',
    period: 'Sep W3',
    month: 'September',
    dateRange: 'Sep 15 - Sep 21',
    dsa: 'Stack, queue, monotonic stack basics',
    fullstack: 'Context, custom hooks, API integration (Axios/Fetch)',
    mobile: 'Navigation (React Navigation: Stack & Tabs)',
    project: 'Build reusable UI component library',
    career: '1 mock interview: Frontend & Core JS fundamentals',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'sep-w4',
    period: 'Sep W4',
    month: 'September',
    dateRange: 'Sep 22 - Sep 30',
    dsa: 'Binary search, search on answers',
    fullstack: 'TypeScript fundamentals in React & state typing',
    mobile: 'AsyncStorage, local persistence, offline state',
    project: 'React app converted to TypeScript with full typing',
    career: 'Update LinkedIn/resume with TS & modern React projects',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w1',
    period: 'Oct W1',
    month: 'October',
    dateRange: 'Oct 1 - Oct 7',
    dsa: 'Sorting algorithms + basic recursion',
    fullstack: 'Node.js + Express setup, routing, middleware',
    mobile: 'RN networking, Fetch/Axios API integration',
    project: 'Create REST API backend with Express & modular routes',
    career: 'Explain backend architecture & Node event loop',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w2',
    period: 'Oct W2',
    month: 'October',
    dateRange: 'Oct 8 - Oct 14',
    dsa: 'Trees basics: Traversal (In/Pre/Post-order, BFS/DFS)',
    fullstack: 'REST API design, request validation (Zod/Joi)',
    mobile: 'Forms + validation in RN (React Hook Form)',
    project: 'CRUD API + React frontend connected end-to-end',
    career: 'Practice API design & system flow explanations',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w3',
    period: 'Oct W3',
    month: 'October',
    dateRange: 'Oct 15 - Oct 21',
    dsa: 'Trees/BST: Height, balance, LCA, range sum',
    fullstack: 'Auth, JWT, bcrypt, secure HTTP cookies',
    mobile: 'Auth flow + secure token storage in mobile app',
    project: 'Login/register authentication system in Full Stack & RN',
    career: '1 mock interview: Full-stack auth & security practices',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w4',
    period: 'Oct W4',
    month: 'October',
    dateRange: 'Oct 22 - Oct 31',
    dsa: 'Graphs basics: Adjacency list, BFS & DFS traversal',
    fullstack: 'Testing, error handling middleware, logging (Winston)',
    mobile: 'Reusable RN UI kit & customized theme system',
    project: 'Documented REST API with Swagger/Postman collection',
    career: 'Portfolio review & GitHub repository presentation polish',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w1',
    period: 'Nov W1',
    month: 'November',
    dateRange: 'Nov 1 - Nov 7',
    dsa: 'Graph algorithms: Cycle detection, topological sort',
    fullstack: 'PostgreSQL setup, relational schemas, SQL queries',
    mobile: 'RN + Postgres-backed API integration',
    project: 'Design database schema with foreign keys & migrations',
    career: 'SQL interview questions (Joins, Indexing, Normalization)',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w2',
    period: 'Nov W2',
    month: 'November',
    dateRange: 'Nov 8 - Nov 14',
    dsa: 'Dynamic programming 1D: Fibonacci, climb stairs, robber',
    fullstack: 'Indexes, query optimization, database constraints',
    mobile: 'State management in RN (Zustand / Redux Toolkit)',
    project: 'Optimize one slow SQL query with indexes and analyze execution',
    career: 'Explain database performance & indexing strategies',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w3',
    period: 'Nov W3',
    month: 'November',
    dateRange: 'Nov 15 - Nov 21',
    dsa: 'DP patterns: 0/1 Knapsack, Coin Change, LCS',
    fullstack: 'Prisma ORM, type-safe queries, seed data',
    mobile: 'FlatList, SectionList optimization & infinite scroll',
    project: 'Prisma-backed CRUD backend with type-safe client',
    career: '1 timed DSA coding assessment under pressure',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w4',
    period: 'Nov W4',
    month: 'November',
    dateRange: 'Nov 22 - Nov 30',
    dsa: 'Mixed DSA revision & speed problem solving',
    fullstack: 'API design, rate limiting, CORS, helmet security',
    mobile: 'RN native device features (Camera/Image Picker/Haptics)',
    project: 'Full-stack dashboard with real-time UI & mobile companion',
    career: 'Mock interview: System design & database modeling',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w1',
    period: 'Dec W1',
    month: 'December',
    dateRange: 'Dec 1 - Dec 7',
    dsa: 'Arrays/strings medium & sliding window revision',
    fullstack: 'Docker, environment variables, Docker Compose',
    mobile: 'RN performance optimization & re-render reduction',
    project: 'Containerize full-stack app with Docker & Compose',
    career: 'Deployment & containerization interview questions',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w2',
    period: 'Dec W2',
    month: 'December',
    dateRange: 'Dec 8 - Dec 14',
    dsa: 'Trees/graphs medium problems revision',
    fullstack: 'VPS/EC2 setup, Nginx reverse proxy, SSL/TLS certs',
    mobile: 'Android build generation (APK / App Bundle preview)',
    project: 'Deploy full-stack project live on VPS / cloud server',
    career: 'Explain cloud hosting, DNS, Nginx reverse proxy in interviews',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w3',
    period: 'Dec W3',
    month: 'December',
    dateRange: 'Dec 15 - Dec 21',
    dsa: 'Mixed hard problems + interview question patterns',
    fullstack: 'CI/CD pipelines (GitHub Actions), structured logs',
    mobile: 'Polish RN app UI/UX, splash screen, app icons',
    project: 'Deploy + configure GitHub Actions automated test & deploy pipeline',
    career: 'Resume + portfolio finalization, start active applications',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w4',
    period: 'Dec W4',
    month: 'December',
    dateRange: 'Dec 22 - Dec 31',
    dsa: 'Final revision: Top 50 DSA patterns & cheat sheets',
    fullstack: 'Architecture + full stack system design deep dive',
    mobile: 'Final RN polish & cross-platform testing',
    project: 'One polished production-ready SaaS/portfolio project live',
    career: '5 mock interviews: Behavioral, coding, system design & offer negotiation',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
];

export const ROADMAP_OUTCOMES = [
  { 
    id: 'o-1', 
    title: 'DSA', 
    target: '60–80 quality problems solved + repeated revision.', 
    icon: 'Binary',
    color: '#6366f1'
  },
  { 
    id: 'o-2', 
    title: 'Full Stack', 
    target: 'React + TypeScript + Node/Express + PostgreSQL + Prisma + auth + API design.', 
    icon: 'Server',
    color: '#10b981'
  },
  { 
    id: 'o-3', 
    title: 'Mobile', 
    target: 'React Native app with navigation, API integration, storage, forms and Android build.', 
    icon: 'Smartphone',
    color: '#06b6d4'
  },
  { 
    id: 'o-4', 
    title: 'DevOps', 
    target: 'Docker + VPS/EC2 + Nginx + HTTPS + environment variables + basic CI/CD.', 
    icon: 'Cloud',
    color: '#f59e0b'
  },
  { 
    id: 'o-5', 
    title: 'Portfolio', 
    target: '1 polished full-stack project + 1 React Native app or mobile client.', 
    icon: 'Briefcase',
    color: '#ec4899'
  },
];
