// Career Roadmap Data (Sep 1 to Dec 31, 2026) with flexible buffer / rest days

export const DEFAULT_ROADMAP = [
  {
    id: 'sep-w1',
    period: 'Sep W1',
    month: 'September',
    dateRange: 'Sep 1 - Sep 7',
    dsa: 'Big-O, arrays, strings',
    fullstack: 'React fundamentals, components, props/state',
    mobile: 'RN setup, components, JSX',
    project: 'Refactor one React module',
    career: 'Git/GitHub cleanup',
    status: 'In Progress', // 'Not Started' | 'In Progress' | 'Completed' | 'Light / Rest Week'
    completedTasks: ['dsa'], // array of keys: 'dsa', 'fullstack', 'mobile', 'project', 'career'
    isLightWeek: false,
    notes: 'Focus on core array algorithms and clean Git commit history.',
  },
  {
    id: 'sep-w2',
    period: 'Sep W2',
    month: 'September',
    dateRange: 'Sep 8 - Sep 14',
    dsa: 'Hash maps, two pointers',
    fullstack: 'Hooks, forms, lifting state',
    mobile: 'Flexbox, styling, core components',
    project: 'Build a small React UI',
    career: 'Explain React concepts aloud',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'sep-w3',
    period: 'Sep W3',
    month: 'September',
    dateRange: 'Sep 15 - Sep 21',
    dsa: 'Stack, queue, linked list',
    fullstack: 'Context, custom hooks, reusable components',
    mobile: 'Navigation + screens',
    project: 'Build reusable component set',
    career: '1 mock technical round',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'sep-w4',
    period: 'Sep W4',
    month: 'September',
    dateRange: 'Sep 22 - Sep 30',
    dsa: 'Binary search, recursion',
    fullstack: 'TypeScript basics, API integration',
    mobile: 'AsyncStorage + API calls',
    project: 'React app using TS + API',
    career: 'Update resume projects',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w1',
    period: 'Oct W1',
    month: 'October',
    dateRange: 'Oct 1 - Oct 7',
    dsa: 'Sorting + intervals',
    fullstack: 'Node.js + Express structure',
    mobile: 'RN networking patterns',
    project: 'Create REST API',
    career: 'Explain backend architecture',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w2',
    period: 'Oct W2',
    month: 'October',
    dateRange: 'Oct 8 - Oct 14',
    dsa: 'Trees basics',
    fullstack: 'REST, validation, error handling',
    mobile: 'Forms + validation',
    project: 'CRUD API + client',
    career: 'Practice API interview Qs',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w3',
    period: 'Oct W3',
    month: 'October',
    dateRange: 'Oct 15 - Oct 21',
    dsa: 'Trees/BST',
    fullstack: 'Auth, JWT, middleware, security basics',
    mobile: 'Auth flow + secure storage concepts',
    project: 'Login/register API + RN screen',
    career: '1 mock interview',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'oct-w4',
    period: 'Oct W4',
    month: 'October',
    dateRange: 'Oct 22 - Oct 31',
    dsa: 'Graphs basics',
    fullstack: 'Testing, logging, API documentation',
    mobile: 'Reusable RN components',
    project: 'Documented API + tests',
    career: 'Portfolio README',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w1',
    period: 'Nov W1',
    month: 'November',
    dateRange: 'Nov 1 - Nov 7',
    dsa: 'Graph traversal',
    fullstack: 'PostgreSQL fundamentals, joins',
    mobile: 'RN + Postgres-backed API integration',
    project: 'Design relational schema',
    career: 'SQL interview practice',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w2',
    period: 'Nov W2',
    month: 'November',
    dateRange: 'Nov 8 - Nov 14',
    dsa: 'Dynamic programming intro',
    fullstack: 'Indexes, transactions, constraints',
    mobile: 'State management patterns',
    project: 'Optimize one DB feature',
    career: 'Explain indexes/transactions',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w3',
    period: 'Nov W3',
    month: 'November',
    dateRange: 'Nov 15 - Nov 21',
    dsa: 'DP patterns + revision',
    fullstack: 'Prisma ORM, migrations, relations',
    mobile: 'FlatList, performance',
    project: 'Prisma-backed feature',
    career: '1 timed DSA set',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'nov-w4',
    period: 'Nov W4',
    month: 'November',
    dateRange: 'Nov 22 - Nov 30',
    dsa: 'Mixed DSA revision',
    fullstack: 'API design, pagination, caching basics',
    mobile: 'RN performance/debugging',
    project: 'Full-stack feature end-to-end',
    career: 'Mock interview',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w1',
    period: 'Dec W1',
    month: 'December',
    dateRange: 'Dec 1 - Dec 7',
    dsa: 'Arrays/strings timed practice',
    fullstack: 'Docker, env vars, production config',
    mobile: 'RN build/release basics',
    project: 'Containerize backend',
    career: 'Deployment questions',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w2',
    period: 'Dec W2',
    month: 'December',
    dateRange: 'Dec 8 - Dec 14',
    dsa: 'Trees/graphs timed practice',
    fullstack: 'VPS/EC2, Nginx, HTTPS, domains',
    mobile: 'Android build + signing concepts',
    project: 'Deploy full-stack app',
    career: 'Explain deployment',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w3',
    period: 'Dec W3',
    month: 'December',
    dateRange: 'Dec 15 - Dec 21',
    dsa: 'Mixed interview set',
    fullstack: 'CI/CD, logs, monitoring, security',
    mobile: 'Polish RN app',
    project: 'Deploy + document project',
    career: 'Resume + portfolio polish',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
  {
    id: 'dec-w4',
    period: 'Dec W4',
    month: 'December',
    dateRange: 'Dec 22 - Dec 31',
    dsa: 'Final revision',
    fullstack: 'Architecture + debugging revision',
    mobile: 'Final RN polish',
    project: 'One polished portfolio project',
    career: '5 mock interview sessions',
    status: 'Not Started',
    completedTasks: [],
    isLightWeek: false,
    notes: '',
  },
];

export const ROADMAP_OUTCOMES = [
  { id: 'o-1', title: 'DSA Mastery', target: '60–80 quality problems solved + repeated revision', icon: 'Binary' },
  { id: 'o-2', title: 'Full Stack Engineering', target: 'React + TypeScript + Node/Express + PostgreSQL + Prisma + Auth + API design', icon: 'Server' },
  { id: 'o-3', title: 'Mobile Development', target: 'React Native app with navigation, API integration, storage, forms & Android release', icon: 'Smartphone' },
  { id: 'o-4', title: 'DevOps & Cloud', target: 'Docker + VPS/EC2 + Nginx + HTTPS + env variables + basic CI/CD', icon: 'Cloud' },
  { id: 'o-5', title: 'Portfolio & Career', target: '1 polished full-stack project + 1 RN app + 10+ mock interview sessions', icon: 'Briefcase' },
];